name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: true 
      matrix:
        os:
          - macos-latest
        ocaml-version:
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: make test
