name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install llvm and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - run: sudo apt install opam
      - run: opam init
      - run: opam install -y llvm.10.0.0
      - run: opam install -y ocamlbuild
      - run: export PATH=$PATH:/usr/local/opt/llvm/bin

      # Add Debug: #TODO Delete this line
      - run: ls /usr/local/opt/llvm/

      - run: sudo ln -s /usr/bin/lli-10 /usr/bin/lli && sudo ln -s /usr/bin/llc-10 /usr/bin/lli
      - run: make test

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK}}
