name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.11.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Cache Opam Dependencies
      #   id: cache-llvm
      #   uses: actions/cache@v2
      #   with:
      #       path: ${{ runner.temp }}/llvm
      #       key: llvm-10.0

      # - name: Install llvm
      #   uses: KyleMayes/install-llvm-action@v1
      #   with:
      #     version: "10.0"
      #     directory: ${{ runner.temp }}/llvm
      #     cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      # - name: Build
        # if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: |
          sudo apt install ocaml llvm-10.0 llvm-10.0-dev llvm-runtime m4 opam
      - run: opam init
      - run: opam install llvm.10.0.0
      - run: eval `opam config env`
      - run: opam install ocamlbuild ocamlfind
      - run: make ci-test && echo SUCCESS

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK}}
