name: Main workflow

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-20.04
        ocaml-version:
          - 4.11.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Use OCaml ${{ matrix.ocaml-version }}
      #   uses: avsm/setup-ocaml@v1
      #   with:
      #     ocaml-version: ${{ matrix.ocaml-version }}

      - run: sudo apt update
      - run: |
          sudo apt install ocaml llvm-10.0 llvm-10.0-dev llvm-runtime m4 opam
      - run: opam init
      - run: opam install llvm.10.0.0
      - run: eval `opam config env`
      - run: opam install ocamlbuild ocamlfind
      - run: make ci-test && echo SUCCESS

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK}}
